name: Build and Test

on:
  workflow_call:
    inputs:
      project_name:
        description: The name of the project.  This should match the NuGet package ID.
        type: string
        required: true

env: {}

jobs:
  setup:
    name: Setup
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure GitHub Packages
        run: nuget sources add -Name GitHub -UserName v-kentro -Password ${{ secrets.GITHUB_TOKEN }} -Source https://nuget.pkg.github.com/v-kentro/index.json -NonInteractive
      - name: NuGet Restore
        run: nuget restore
      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: packages/
  build:
    name: Build
    runs-on: windows-2022
    needs:
      - setup
    strategy:
      matrix:
        platform:
          - x86
          - x64
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Packages
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages/
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build
        run: msbuild ${{ inputs.project_name }}.sln -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.configuration }}-${{ matrix.platform }}
          path: |
            x64/
            Debug/
            Release/
  test:
    name: Test
    runs-on: windows-2022
    needs:
      - build
    strategy:
      matrix:
        platform:
          - x86
          - x64
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.configuration }}-${{ matrix.platform }}
      - name: Run Tests
        uses: microsoft/vstest-action@v1.0.0
        with:
          searchFolder: '.\\'
          testAssembly: '**\\*test*.dll'
          codeCoverageEnabled: false
